name: Git Action Test

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: test with maven
        run: mvn -B verify --file pom.xml
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)
  revision:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - if: github.event.release
        name: Update version in pom.xml (Release only)
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
      - if: github.event.release
        name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -am "chore: update pom version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:main
  deploy:
    runs-on: ubuntu-latest
    needs: revision
    steps:
      - name: deploy
        run: echo "Dummy Deploy"
    
  
